name: clickresturant
description: "A Flutter project for mange your restaurant's online and sell goods easily and by one click  ."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  dio: ^5.4.0
  flutter_screenutil: ^5.9.0
  carousel_slider: ^5.1.1
  
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.3
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  cloud_firestore: ^5.6.12
  http: 
  internet_connection_checker: 
  geolocator: 
  geocoding: 
  flutter_map:
  latlong2: ^0.9.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/products/
    - assets/icons/
